### PR TITLE
Bugfix - cesium is not a function

### PR DESCRIPTION
**Pull request by amitgk1**

### CODE REVIEW

**Comment by amitgk1** [comment]
when working in a vite project with:

- `package.json` with the property `type: "module"`
- vite config TS file i.e `vite.config.ts`
- might be another issue - I'm using vite version 3

the following config throws an error:
```typescript
import {defineConfig} from "vite"
import cesium from "vite-plugin-cesium"

export default defineConfig({
    plugins: [cesium()]
})
```
the thrown error is "cesium is not  a function"

this PR fixes that behavior by using the npm package tsdv (inspired by `vite-plugin-svgr`).
by using tsdv we can build our project for different formats (es, umd, etc.) thus supporting my use case

**Comment by nshen** [comment]
Thanks so much, I'll try it later today.

**Comment by nshen** [comment]
hi, @amitgk1 seems like [tsdv](https://www.npmjs.com/package/tsdv) is not even an open source project, would you like to change to tsup or something else?

**Comment by amitgk1** [comment]
@nshen you're right, didn't notice 😅
I'll look into it later

**Comment by amitgk1** [comment]
Seems like it's open source after all - [https://github.com/pd4d10/tsdv/tree/main]()

I assume he just forgot or didn't know to add the repository field in his package.json like so [https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository]()

**Comment by nshen** [comment]
It seems to work on my mac, not sure why these build tests failed.

**Comment by amitgk1** [comment]
Thanks a lot!

Didn't had the time to invest in fixing those but it seems moving to tsup definitely was the right solution.

I just wanna say this was my first contribution to the open source community and you've made it a good experience 🙏🏻

**Pull request merged**
